# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml

baseurl                 = "https://coding-corner.netlify.app/"
DefaultContentLanguage  = "en"
title                   = "My Coding Corner"
theme                   = "hugo-future-imperfect-slim"
paginate                = 5
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []
enableEmoji             = true

[outputs]
    home = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default", "css/add-on.css", "css/highlight.css"]
  jsFiles               = ["default"]
  highlightjs           = false
  highlightjsTheme      = "github"
  highlightjsLang       = ["r", "python", "julia", "bash", "html", "css", "js", "toml", "yaml"]
  viewMorePostsLink     = "/post/"
  readingTime           = false
  # socialShare           = ["twitter", "facebook", "reddit", "linkedin",
  #                         "pinterest", "email"]

  [params.meta]
    description         = "My Data Science Learning Journal"
    author              = "Luca Baggi"
    favicon             = false
    svg                 = false
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "My Coding Corner"
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = false
    languageMenu        = false

  [params.intro]
    header                = "My Coding Corner"
    paragraph             = "My Data Science Learning Journal"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = ""
      shape               = ""
      width               = ""
      alt                 = ""

  [params.sidebar]
    about               = 'Powered by <a href="//gohugo.io">Hugo</a> and <a href="https://github.com/r-lib/hugodown">hugodown</a>. </br></br> This content of this blog is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a> except where stated otherwise.'
    postAmount          = 5
    categories          = false
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = false

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/post/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 2

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 3

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  # Coding Communities
  github                = "baggiponte"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "lucabaggi1997"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "lucabaggi1997"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = ""

# hugodown
ignoreFiles = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$', "\\.Rmd$", "\\.Rmarkdown$"]
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true